spring.application.name=casino-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/casino-platform
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.user.password = demo@123
spring.security.user.name = admin
app.jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
app.jwt.expiration=86400000
